[project]
name = "iniad-cs2-django"
version = "0.1.0"
description = "Computer-Science-II Lecture at INIAD with Django"
authors = [
    { name = "mst-mkt", email = "s1f102303057@iniad.org" }
]
dependencies = [
    "django>=4.2.7",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ruff>=0.1.6",
    "mypy>=1.7.0",
]

[tool.hatch.metadata]
allow-direct-references = true
