name: Lint and Type check

on: [push]

jobs:
  lint-and-typecheck:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install Rye
        uses: baptiste0928/cargo-install@v2
        with:
          crate: rye
          git: https://github.com/mitsuhiko/rye
          branch: main
      - name: Install Dependencies
        run: rye sync
      - name: Lint
        run: rye run lint
      - name: TypeCheck
        run: rye run typecheck
